from django.contrib import admin
from CMS.models import *
# Register your models here.
admin.site.register(CaneClassMaster)
admin.site.register(CaneQualityMaster)
admin.site.register(PlantTypeMaster)
admin.site.register(RegTypeMaster)
admin.site.register(LaganTypeMaster)
admin.site.register(GatTypeMaster)
admin.site.register(GatMaster)
admin.site.register(VillageGats)
admin.site.register(HangamMaster)
admin.site.register(SubVillageMaster)
admin.site.register(SubVillageRoutes)
admin.site.register(SpPermissionMaster)
admin.site.register(WaterSupplyMaster)
admin.site.register(WaterSchemeMaster)
admin.site.register(SeasonYearMaster)
admin.site.register(OtherUse)
admin.site.register(CaneRegistration)
admin.site.register(CaneRegistrationPhotos)
admin.site.register(CaneRegistrationCoOrdinate)
admin.site.register(HamipatraMaster)
admin.site.register(HamipatraDetails)
admin.site.register(CaneCertificate)
admin.site.register(CaneCertificateDetails)
admin.site.register(CaneSampling)
admin.site.register(TransporterTypeMaster)
admin.site.register(TransporterMaster)
admin.site.register(TranVehicleMaster)
admin.site.register(HarvesterMaster)
admin.site.register(WeightSlips)
admin.site.register(WeightSlip_Mobile)
admin.site.register(WeightSlip_Mobile_Details)
admin.site.register(HarvestingProgram)